const fs = require('fs');
const lines = [];
lines.push("const express = require('express');");
lines.push("const multer = require('multer');");
lines.push("const sgMail = require('@sendgrid/mail');");
lines.push("const cors = require('cors');");
lines.push("const path = require('path');");
lines.push("const fs = require('fs');");
lines.push("const { google } = require('googleapis');");
lines.push("const { OAuth2Client } = require('google-auth-library');");
lines.push("require('dotenv').config();");
lines.push("const app = express();");
lines.push("app.use(cors());");
lines.push("app.use(express.json());");
lines.push("app.use(express.static(path.join(__dirname, 'public')));");
lines.push("sgMail.setApiKey(process.env.SENDGRID_API_KEY);");
lines.push("const uploadPath = process.env.UPLOAD_PATH || path.join(__dirname, 'uploads');");
lines.push("if (!fs.existsSync(uploadPath)) fs.mkdirSync(uploadPath, { recursive: true });");
lines.push("const storage = multer.diskStorage({ destination: (req, file, cb) => cb(null, uploadPath), filename: (req, file, cb) => { const unique = Date.now() + '-' + Math.round(Math.random() * 1e9); cb(null, unique + path.extname(file.originalname)); } });");
lines.push("const upload = multer({ storage });");
lines.push("const oauth2Client = new OAuth2Client(process.env.GOOGLE_CLIENT_ID, process.env.GOOGLE_CLIENT_SECRET, process.env.REDIRECT_URI);");
lines.push("if (process.env.GOOGLE_REFRESH_TOKEN) { oauth2Client.setCredentials({ refresh_token: process.env.GOOGLE_REFRESH_TOKEN }); }");
lines.push("app.get('/auth', (req, res) => {");
lines.push("  const url = oauth2Client.generateAuthUrl({ access_type: 'offline', scope: ['https://www.googleapis.com/auth/drive.file', 'https://www.googleapis.com/auth/spreadsheets'], prompt: 'consent' });");
lines.push("  res.redirect(url);");
lines.push("});");
lines.push("app.get('/auth/callback', async (req, res) => {");
lines.push("  try {");
lines.push("    const { tokens } = await oauth2Client.getToken(req.query.code);");
lines.push("    oauth2Client.setCredentials(tokens);");
lines.push("    res.send('<h2>Authorization successful!</h2><p>Refresh token: <b>' + tokens.refresh_token + '</b></p><p>Copy this token and add it to Render as GOOGLE_REFRESH_TOKEN, then you can close this page.</p>');");
lines.push("  } catch (err) { res.send('Error: ' + err.message); }");
lines.push("});");
lines.push("async function uploadToDrive(filePath, filename, unit) {");
lines.push("  try {");
lines.push("    const drive = google.drive({ version: 'v3', auth: oauth2Client });");
lines.push("    const folderRes = await drive.files.list({ q: \"name='Unit \" + unit + \"' and mimeType='application/vnd.google-apps.folder' and '\" + process.env.DRIVE_FOLDER_ID + \"' in parents and trashed=false\", fields: 'files(id, name)' });");
lines.push("    let unitFolderId;");
lines.push("    if (folderRes.data.files.length > 0) { unitFolderId = folderRes.data.files[0].id; }");
lines.push("    else { const newFolder = await drive.files.create({ requestBody: { name: 'Unit ' + unit, mimeType: 'application/vnd.google-apps.folder', parents: [process.env.DRIVE_FOLDER_ID] }, fields: 'id' }); unitFolderId = newFolder.data.id; }");
lines.push("    const fileRes = await drive.files.create({ requestBody: { name: filename, parents: [unitFolderId] }, media: { mimeType: 'image/jpeg', body: fs.createReadStream(filePath) }, fields: 'id, webViewLink' });");
lines.push("    return fileRes.data.webViewLink;");
lines.push("  } catch (err) { console.error('Drive upload error:', err.message); return null; }");
lines.push("}");
lines.push("async function logToSheet(unit, tenant, inspector, officeEmail, damages, total) {");
lines.push("  try {");
lines.push("    const sheets = google.sheets({ version: 'v4', auth: oauth2Client });");
lines.push("    const damageList = damages.map(d => d.room + ' - ' + d.damage + ' ($' + d.price + ')').join(', ');");
lines.push("    await sheets.spreadsheets.values.append({ spreadsheetId: process.env.GOOGLE_SHEET_ID, range: 'Sheet1!A:G', valueInputOption: 'USER_ENTERED', requestBody: { values: [[new Date().toLocaleDateString(), unit, tenant || 'N/A', inspector, officeEmail, '$' + total.toFixed(2), damageList]] } });");
lines.push("  } catch (err) { console.error('Sheet log error:', JSON.stringify(err.message), JSON.stringify(err.response && err.response.data)); }");
lines.push("}");
lines.push("app.post('/upload', upload.single('photo'), (req, res) => {");
lines.push("  if (!req.file) return res.status(400).json({ error: 'No file uploaded' });");
lines.push("  res.json({ filename: req.file.filename, path: req.file.path });");
lines.push("});");
lines.push("app.post('/send-report', async (req, res) => {");
lines.push("  const { unit, tenant, inspector, inspectorEmail, officeEmail, damages } = req.body;");
lines.push("  let html = '<h2>Inspection Report</h2>';");
lines.push("  html += '<p><b>Unit:</b> ' + unit + '</p>';");
lines.push("  html += '<p><b>Tenant:</b> ' + (tenant || 'N/A') + '</p>';");
lines.push("  html += '<p><b>Inspector:</b> ' + inspector + '</p>';");
lines.push("  html += '<p><b>Date:</b> ' + new Date().toLocaleDateString() + '</p>';");
lines.push("  html += '<h3>Damages</h3>';");
lines.push("  html += '<table border=\"1\" cellpadding=\"6\" cellspacing=\"0\">';");
lines.push("  html += '<tr><th>Room</th><th>Damage</th><th>Charge</th><th>Notes</th><th>Photo</th></tr>';");
lines.push("  let total = 0;");
lines.push("  const attachments = [];");
lines.push("  for (const d of damages) {");
lines.push("    let driveLink = '';");
lines.push("    if (d.filename) {");
lines.push("      const filePath = path.join(uploadPath, d.filename);");
lines.push("      if (fs.existsSync(filePath)) {");
lines.push("        const fileData = fs.readFileSync(filePath);");
lines.push("        attachments.push({ content: fileData.toString('base64'), filename: d.filename, type: 'image/jpeg', disposition: 'attachment' });");
lines.push("        const link = await uploadToDrive(filePath, d.filename, unit);");
lines.push("        if (link) driveLink = '<a href=\"' + link + '\">View Photo</a>';");
lines.push("      }");
lines.push("    }");
lines.push("    html += '<tr><td>' + d.room + '</td><td>' + d.damage + '</td><td>$' + d.price + '</td><td>' + (d.notes || '') + '</td><td>' + driveLink + '</td></tr>';");
lines.push("    total += parseFloat(d.price) || 0;");
lines.push("  }");
lines.push("  html += '<tr><td colspan=\"3\"><b>Total</b></td><td><b>$' + total.toFixed(2) + '</b></td><td></td></tr></table>';");
lines.push("  const confirmHtml = '<h2>Report Confirmation</h2><p>Hi ' + inspector + ',</p><p>Report for Unit ' + unit + ' submitted.</p><p>Tenant: ' + (tenant || 'N/A') + '</p><p>Date: ' + new Date().toLocaleDateString() + '</p><p>Damages: ' + damages.length + '</p><p>Total: $' + total.toFixed(2) + '</p><p>Report and photos sent to office and uploaded to Google Drive.</p>';");
lines.push("  try {");
lines.push("    if (!officeEmail) throw new Error('No office email provided');");
lines.push("    const officeEmails = officeEmail.split(',').map(e => e.trim()).filter(e => e);");
lines.push("    await sgMail.send({ from: process.env.EMAIL_FROM, to: officeEmails, subject: 'Inspection Report - Unit ' + unit, html: html, attachments: attachments });");
lines.push("    if (inspectorEmail) await sgMail.send({ from: process.env.EMAIL_FROM, to: inspectorEmail, subject: 'Confirmation - Report sent for Unit ' + unit, html: confirmHtml });");
lines.push("    await logToSheet(unit, tenant, inspector, officeEmail, damages, total);");
lines.push("    res.json({ success: true });");
lines.push("  } catch (err) { console.error(err.response ? err.response.body : err); res.status(500).json({ error: err.message }); }");
lines.push("});");
lines.push("app.listen(process.env.PORT || 3001, function() { console.log('Inspection server running on port ' + (process.env.PORT || 3001)); console.log('Upload folder: ' + uploadPath); });");
fs.writeFileSync('server.js', lines.join('\n'));
console.log('Done! server.js written with ' + lines.length + ' lines.');