const fs = require('fs');
const lines = [];
lines.push("const express = require('express');");
lines.push("const multer = require('multer');");
lines.push("const sgMail = require('@sendgrid/mail');");
lines.push("const cors = require('cors');");
lines.push("const path = require('path');");
lines.push("const fs = require('fs');");
lines.push("const { google } = require('googleapis');");
lines.push("require('dotenv').config();");
lines.push("const app = express();");
lines.push("app.use(cors());");
lines.push("app.use(express.json());");
lines.push("app.use(express.static(path.join(__dirname, 'public')));");
lines.push("sgMail.setApiKey(process.env.SENDGRID_API_KEY);");
lines.push("const uploadPath = process.env.UPLOAD_PATH || path.join(__dirname, 'uploads');");
lines.push("if (!fs.existsSync(uploadPath)) fs.mkdirSync(uploadPath, { recursive: true });");
lines.push("const storage = multer.diskStorage({ destination: (req, file, cb) => cb(null, uploadPath), filename: (req, file, cb) => { const unique = Date.now() + '-' + Math.round(Math.random() * 1e9); cb(null, unique + path.extname(file.originalname)); } });");
lines.push("const upload = multer({ storage });");
lines.push("async function uploadToDrive(filePath, filename, unit) {");
lines.push("  try {");
lines.push("    const credentials = process.env.GOOGLE_CREDENTIALS ? JSON.parse(process.env.GOOGLE_CREDENTIALS) : JSON.parse(fs.readFileSync(path.join(__dirname, 'credentials.json')));");
lines.push("    const auth = new google.auth.GoogleAuth({ credentials, scopes: ['https://www.googleapis.com/auth/drive'] });");
lines.push("    const drive = google.drive({ version: 'v3', auth });");
lines.push("    const folderRes = await drive.files.list({ q: \"name='Unit \" + unit + \"' and mimeType='application/vnd.google-apps.folder' and '\" + process.env.DRIVE_FOLDER_ID + \"' in parents and trashed=false\", fields: 'files(id, name)', supportsAllDrives: true, includeItemsFromAllDrives: true });");
lines.push("    let unitFolderId;");
lines.push("    if (folderRes.data.files.length > 0) { unitFolderId = folderRes.data.files[0].id; }");
lines.push("    else { const newFolder = await drive.files.create({ requestBody: { name: 'Unit ' + unit, mimeType: 'application/vnd.google-apps.folder', parents: [process.env.DRIVE_FOLDER_ID] }, fields: 'id', supportsAllDrives: true }); unitFolderId = newFolder.data.id; }");
lines.push("    const fileRes = await drive.files.create({ requestBody: { name: filename, parents: [unitFolderId] }, media: { mimeType: 'image/jpeg', body: fs.createReadStream(filePath) }, fields: 'id, webViewLink', supportsAllDrives: true });");
lines.push("    return fileRes.data.webViewLink;");
lines.push("  } catch (err) { console.error('Drive upload error:', err.message); return null; }");
lines.push("}");
lines.push("app.post('/upload', upload.single('photo'), (req, res) => {");
lines.push("  if (!req.file) return res.status(400).json({ error: 'No file uploaded' });");
lines.push("  res.json({ filename: req.file.filename, path: req.file.path });");
lines.push("});");
lines.push("app.post('/send-report', async (req, res) => {");
lines.push("  const { unit, tenant, inspector, inspectorEmail, officeEmail, damages } = req.body;");
lines.push("  let html = '<h2>Inspection Report</h2>';");
lines.push("  html += '<p><b>Unit:</b> ' + unit + '</p>';");
lines.push("  html += '<p><b>Tenant:</b> ' + tenant + '</p>';");
lines.push("  html += '<p><b>Inspector:</b> ' + inspector + '</p>';");
lines.push("  html += '<p><b>Date:</b> ' + new Date().toLocaleDateString() + '</p>';");
lines.push("  html += '<h3>Damages</h3>';");
lines.push("  html += '<table border=\"1\" cellpadding=\"6\" cellspacing=\"0\">';");
lines.push("  html += '<tr><th>Room</th><th>Damage</th><th>Charge</th><th>Notes</th><th>Photo</th></tr>';");
lines.push("  let total = 0;");
lines.push("  const attachments = [];");
lines.push("  for (const d of damages) {");
lines.push("    let driveLink = '';");
lines.push("    if (d.filename) {");
lines.push("      const filePath = path.join(uploadPath, d.filename);");
lines.push("      if (fs.existsSync(filePath)) {");
lines.push("        const fileData = fs.readFileSync(filePath);");
lines.push("        attachments.push({ content: fileData.toString('base64'), filename: d.filename, type: 'image/jpeg', disposition: 'attachment' });");
lines.push("        const link = await uploadToDrive(filePath, d.filename, unit);");
lines.push("        if (link) driveLink = '<a href=\"' + link + '\">View Photo</a>';");
lines.push("      }");
lines.push("    }");
lines.push("    html += '<tr><td>' + d.room + '</td><td>' + d.damage + '</td><td>$' + d.price + '</td><td>' + (d.notes || '') + '</td><td>' + driveLink + '</td></tr>';");
lines.push("    total += parseFloat(d.price) || 0;");
lines.push("  }");
lines.push("  html += '<tr><td colspan=\"3\"><b>Total</b></td><td><b>$' + total.toFixed(2) + '</b></td><td></td></tr></table>';");
lines.push("  const confirmHtml = '<h2>Report Confirmation</h2><p>Hi ' + inspector + ',</p><p>Report for Unit ' + unit + ' submitted.</p><p>Tenant: ' + tenant + '</p><p>Date: ' + new Date().toLocaleDateString() + '</p><p>Damages: ' + damages.length + '</p><p>Total: $' + total.toFixed(2) + '</p><p>Report and photos sent to office and uploaded to Google Drive.</p>';");
lines.push("  try {");
lines.push("    if (!officeEmail) throw new Error('No office email provided');");
lines.push("    await sgMail.send({ from: process.env.EMAIL_FROM, to: officeEmail, subject: 'Inspection Report - Unit ' + unit, html: html, attachments: attachments });");
lines.push("    if (inspectorEmail) await sgMail.send({ from: process.env.EMAIL_FROM, to: inspectorEmail, subject: 'Confirmation - Report sent for Unit ' + unit, html: confirmHtml });");
lines.push("    res.json({ success: true });");
lines.push("  } catch (err) { console.error(err.response ? err.response.body : err); res.status(500).json({ error: err.message }); }");
lines.push("});");
lines.push("app.listen(process.env.PORT || 3001, function() { console.log('Inspection server running on port ' + (process.env.PORT || 3001)); console.log('Upload folder: ' + uploadPath); });");
fs.writeFileSync('server.js', lines.join('\n'));
console.log('Done! server.js written with ' + lines.length + ' lines.');